"""
AWS CloudWatch Webhook Receiver

Accepts AWS SNS/CloudWatch alarm notifications and feeds them directly
into the full AI agent pipeline — no email needed.

HOW TO CONNECT IN AWS:
  1. Go to AWS SNS → Create Topic → Standard
  2. Create Subscription → Protocol: HTTPS
  3. Endpoint: https://YOUR_SERVER/api/webhook/aws
  4. Your server auto-confirms the subscription
  5. Go to CloudWatch → Alarms → select alarm → Actions → Send to SNS topic

PAYLOAD TYPES HANDLED:
  - SubscriptionConfirmation  (auto-confirms so AWS knows endpoint is valid)
  - Notification              (actual CloudWatch alarm firing)
  - UnsubscribeConfirmation   (graceful unsubscribe)

TEST WITHOUT AWS:
  POST /api/webhook/aws/test  (simulates a P1 CPU alarm)
"""

import json
import logging
import asyncio
import uuid as _uuid
from datetime import datetime
from typing import Any, Dict
from fastapi import APIRouter, Request, BackgroundTasks, HTTPException
from fastapi.responses import JSONResponse

logger  = logging.getLogger(__name__)
router  = APIRouter()

# Track last 20 webhook events for the dashboard
_webhook_log: list = []


def _log_event(source: str, alarm_name: str, state: str, detail: str) -> None:
    """Store webhook event for dashboard display."""
    _webhook_log.insert(0, {
        "id":         str(_uuid.uuid4())[:8],
        "source":     source,
        "alarm_name": alarm_name,
        "state":      state,
        "detail":     detail[:120],
        "received_at": datetime.now().strftime("%H:%M:%S"),
    })
    if len(_webhook_log) > 20:
        _webhook_log.pop()


def _cloudwatch_to_email(alarm: Dict[str, Any]) -> str:
    """
    Convert a CloudWatch alarm payload into an email-like text
    that the AI pipeline understands.
    """
    alarm_name   = alarm.get("AlarmName",        "Unknown Alarm")
    description  = alarm.get("AlarmDescription", "No description")
    state        = alarm.get("NewStateValue",    "ALARM")
    reason       = alarm.get("NewStateReason",   "")
    region       = alarm.get("Region",           "unknown region")
    state_time   = alarm.get("StateChangeTime",  "")

    # Extract metric info
    trigger      = alarm.get("Trigger", {})
    metric       = trigger.get("MetricName", "Unknown Metric")
    namespace    = trigger.get("Namespace",  "Unknown Service")
    threshold    = trigger.get("Threshold",  "N/A")
    dimensions   = trigger.get("Dimensions", [])
    dim_str      = ", ".join(
        f"{d.get('name','?')}={d.get('value','?')}" for d in dimensions
    ) or "N/A"

    # Determine severity
    priority_hint = ""
    name_lower    = alarm_name.lower()
    if any(w in name_lower for w in ["critical", "p1", "down", "outage", "crash"]):
        priority_hint = "CRITICAL PRIORITY — P1"
    elif any(w in name_lower for w in ["high", "p2", "error", "fail"]):
        priority_hint = "HIGH PRIORITY — P2"
    else:
        priority_hint = "MEDIUM PRIORITY — P3"

    return f"""From: AWS CloudWatch <cloudwatch@aws.amazon.com>
Subject: AWS ALARM: {alarm_name} — {state}
X-Source: aws-cloudwatch
X-Alarm-State: {state}

{priority_hint}

AWS CloudWatch Alarm Triggered
================================
Alarm Name  : {alarm_name}
Description : {description}
State       : {state}
Region      : {region}
Time        : {state_time}

Metric Details:
  Metric    : {metric}
  Namespace : {namespace}
  Threshold : {threshold}
  Dimensions: {dim_str}

Reason:
{reason}

Please investigate and resolve this alarm immediately.
This alert was automatically generated by AWS CloudWatch
and forwarded to the AI Operations Center for processing.
"""


async def _run_pipeline(raw_text: str, alarm_name: str, state: str) -> None:
    """Run the full AI agent pipeline on the alarm — in background."""
    from app.agents.manager import build_manager_graph
    from app.core.results_store import store_result
    from app.services.email_reply import send_reply
    import time as _time

    subject = f"AWS ALARM: {alarm_name} — {state}"
    sender  = "cloudwatch@aws.amazon.com"

    graph        = build_manager_graph()
    thread_id    = str(_uuid.uuid4())
    initial_state = {
        "raw_email":         raw_text,
        "email_data":        {},
        "workflow_plan":     {},
        "incident_result":   {},
        "knowledge_results": {},
        "ticket_result":     {},
        "meeting_result":    {},
        "executive_summary": "",
        "human_approved":    False,
    }
    config = {"configurable": {"thread_id": thread_id}}

    try:
        t0        = _time.monotonic()
        result    = await graph.ainvoke(initial_state, config=config)
        elapsed   = int((_time.monotonic() - t0) * 1000)

        reply_sent = False
        try:
            reply_sent = await send_reply(
                original_sender=sender,
                original_subject=subject,
                result=result or {},
                uid=f"webhook-aws-{thread_id}",
            )
        except Exception as re:
            logger.warning(f"[Webhook/AWS] Reply failed: {re}")

        store_result(subject, sender, result or {},
                     process_ms=elapsed, reply_sent=reply_sent)

        # Post-mortem for P1
        priority = (result or {}).get("email_data", {}).get("priority", "")
        if priority == "P1-critical":
            try:
                from app.services.pdf_postmortem import send_postmortem
                asyncio.create_task(
                    send_postmortem(subject=subject, result=result or {})
                )
            except Exception:
                pass

        logger.info(
            f"[Webhook/AWS] ✅ Pipeline done: {subject[:60]} | "
            f"reply={'✅' if reply_sent else '❌'} | {elapsed}ms"
        )

    except Exception as e:
        logger.error(f"[Webhook/AWS] Pipeline failed: {e}")


# ── Routes ─────────────────────────────────────────────────────────────────────

@router.post("/webhook/aws")
async def aws_cloudwatch_webhook(
    request:          Request,
    background_tasks: BackgroundTasks,
) -> JSONResponse:
    """
    Main AWS SNS/CloudWatch webhook endpoint.
    AWS requires a 200 response within 15 seconds — pipeline runs in background.
    """
    # Parse body — AWS sends JSON
    try:
        body = await request.json()
    except Exception:
        raw = await request.body()
        logger.warning(f"[Webhook/AWS] Could not parse JSON: {raw[:200]}")
        return JSONResponse({"status": "ignored", "reason": "invalid json"})

    msg_type = body.get("Type", "")
    logger.info(f"[Webhook/AWS] Received SNS message type: {msg_type}")

    # ── Handle subscription confirmation ─────────────────────────────────────
    if msg_type == "SubscriptionConfirmation":
        subscribe_url = body.get("SubscribeURL", "")
        if subscribe_url:
            try:
                import httpx
                async with httpx.AsyncClient(timeout=10) as client:
                    await client.get(subscribe_url)
                logger.info("[Webhook/AWS] ✅ SNS subscription confirmed automatically")
                _log_event("AWS SNS", "Subscription", "CONFIRMED",
                           "SNS subscription confirmed — AWS is now connected")
            except Exception as e:
                logger.warning(f"[Webhook/AWS] Auto-confirm failed: {e}")
        return JSONResponse({"status": "confirmed"})

    # ── Handle actual alarm notification ─────────────────────────────────────
    if msg_type == "Notification":
        subject     = body.get("Subject", "AWS CloudWatch Notification")
        raw_message = body.get("Message", "{}")

        # Message is a JSON string inside the SNS envelope
        try:
            alarm = json.loads(raw_message)
        except json.JSONDecodeError:
            alarm = {"AlarmName": subject, "NewStateValue": "ALARM",
                     "NewStateReason": raw_message}

        alarm_name = alarm.get("AlarmName",     subject)
        state      = alarm.get("NewStateValue", "ALARM")
        reason     = alarm.get("NewStateReason","")

        logger.warning(f"[Webhook/AWS] 🚨 Alarm: {alarm_name} → {state}")
        _log_event("AWS CloudWatch", alarm_name, state, reason)

        # Only process ALARM state (not OK recovery)
        if state == "ALARM":
            raw_email = _cloudwatch_to_email(alarm)
            background_tasks.add_task(_run_pipeline, raw_email, alarm_name, state)
            return JSONResponse({
                "status":     "processing",
                "alarm":      alarm_name,
                "state":      state,
                "message":    "AI pipeline triggered in background",
            })
        else:
            # State is OK — alarm resolved
            logger.info(f"[Webhook/AWS] ✅ Alarm resolved: {alarm_name}")
            # Mark resolved in SQLite
            try:
                from app.core.db import mark_resolved
                # best-effort — alarm name match
            except Exception:
                pass
            return JSONResponse({
                "status":  "ok",
                "alarm":   alarm_name,
                "message": "Alarm resolved — no pipeline needed",
            })

    return JSONResponse({"status": "ignored", "type": msg_type})


@router.get("/webhook/events")
async def get_webhook_events():
    """Returns recent webhook events for dashboard display."""
    return {"events": _webhook_log}


@router.post("/webhook/aws/test")
async def test_aws_webhook(background_tasks: BackgroundTasks) -> JSONResponse:
    """
    Test endpoint — simulates a real AWS P1 CPU alarm.
    Call this to verify your pipeline works WITHOUT needing real AWS.

    Usage:
      curl -X POST http://localhost:8000/api/webhook/aws/test
    """
    fake_alarm = {
        "AlarmName":        "Production-CPU-Critical",
        "AlarmDescription": "CPU utilization exceeded 95% for 5 minutes on production servers",
        "NewStateValue":    "ALARM",
        "NewStateReason":   "Threshold Crossed: 1 out of 1 datapoints [97.3%] >= threshold (95.0%)",
        "StateChangeTime":  datetime.now().isoformat() + "Z",
        "Region":           "US East (N. Virginia)",
        "Trigger": {
            "MetricName":          "CPUUtilization",
            "Namespace":           "AWS/EC2",
            "Threshold":           95.0,
            "ComparisonOperator":  "GreaterThanOrEqualToThreshold",
            "Dimensions": [
                {"name": "InstanceId", "value": "i-0abc123def456"},
                {"name": "AutoScalingGroupName", "value": "prod-api-asg"},
            ],
        },
    }

    logger.info("[Webhook/AWS] 🧪 Running TEST alarm simulation")
    _log_event("AWS CloudWatch [TEST]", "Production-CPU-Critical",
               "ALARM", "Test simulation — CPU at 97.3%")

    raw_email = _cloudwatch_to_email(fake_alarm)
    background_tasks.add_task(
        _run_pipeline, raw_email, "Production-CPU-Critical [TEST]", "ALARM"
    )

    return JSONResponse({
        "status":  "test_triggered",
        "message": "Simulated P1 CPU alarm — check dashboard in ~30 seconds",
        "alarm":   "Production-CPU-Critical",
        "tip":     "Watch the Auto-Processed Inbox on your dashboard",
    })
